/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as TimerOrgSlugRouteImport } from './routes/timer/$orgSlug'
import { Route as OverlayOrgSlugRouteImport } from './routes/overlay/$orgSlug'
import { Route as InviteInvitationIdRouteImport } from './routes/invite/$invitationId'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthInvitationsRouteImport } from './routes/_auth/invitations'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as SlugTimecodeRouteImport } from './routes/$slug/timecode'
import { Route as SlugTeamRouteImport } from './routes/$slug/team'
import { Route as SlugShowRouteImport } from './routes/$slug/show'
import { Route as SlugSettingsRouteImport } from './routes/$slug/settings'
import { Route as SlugRundownRouteImport } from './routes/$slug/rundown'
import { Route as SlugCrewChatRouteImport } from './routes/$slug/crew-chat'
import { Route as SlugCheckinRouteImport } from './routes/$slug/checkin'
import { Route as SlugChatRouteImport } from './routes/$slug/chat'
import { Route as SlugBoardRouteImport } from './routes/$slug/board'
import { Route as SlugAdminRouteImport } from './routes/$slug/admin'
import { Route as ApiWaitlistIndexRouteImport } from './routes/api/waitlist/index'
import { Route as ApiOverlayOrgSlugRouteImport } from './routes/api/overlay/$orgSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SlugStreamingPlatformsRouteImport } from './routes/$slug/streaming/platforms'
import { Route as SlugStreamingLtPreviewRouteImport } from './routes/$slug/streaming/lt-preview'
import { Route as SlugStreamingHealthRouteImport } from './routes/$slug/streaming/health'
import { Route as SlugStreamingGraphicsRouteImport } from './routes/$slug/streaming/graphics'
import { Route as SlugProductionIncidentsRouteImport } from './routes/$slug/production/incidents'
import { Route as SlugProductionCueSheetsRouteImport } from './routes/$slug/production/cue-sheets'
import { Route as SlugProductionChecklistRouteImport } from './routes/$slug/production/checklist'
import { Route as SlugProductionAssetsRouteImport } from './routes/$slug/production/assets'
import { Route as SlugDashboardTechManagerRouteImport } from './routes/$slug/dashboard/tech-manager'
import { Route as SlugDashboardProdManagerRouteImport } from './routes/$slug/dashboard/prod-manager'
import { Route as SlugDashboardDevicesRouteImport } from './routes/$slug/dashboard/devices'
import { Route as SlugDashboardAudioRouteImport } from './routes/$slug/dashboard/audio'
import { Route as SlugStreamingGraphicsOverlayRouteImport } from './routes/$slug/streaming/graphics/overlay'
import { Route as SlugDashboardDevicesDeviceIdRouteImport } from './routes/$slug/dashboard/devices.$deviceId'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const TimerOrgSlugRoute = TimerOrgSlugRouteImport.update({
  id: '/timer/$orgSlug',
  path: '/timer/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayOrgSlugRoute = OverlayOrgSlugRouteImport.update({
  id: '/overlay/$orgSlug',
  path: '/overlay/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvitationsRoute = AuthInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const SlugTimecodeRoute = SlugTimecodeRouteImport.update({
  id: '/timecode',
  path: '/timecode',
  getParentRoute: () => SlugRoute,
} as any)
const SlugTeamRoute = SlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SlugRoute,
} as any)
const SlugShowRoute = SlugShowRouteImport.update({
  id: '/show',
  path: '/show',
  getParentRoute: () => SlugRoute,
} as any)
const SlugSettingsRoute = SlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SlugRoute,
} as any)
const SlugRundownRoute = SlugRundownRouteImport.update({
  id: '/rundown',
  path: '/rundown',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCrewChatRoute = SlugCrewChatRouteImport.update({
  id: '/crew-chat',
  path: '/crew-chat',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCheckinRoute = SlugCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => SlugRoute,
} as any)
const SlugChatRoute = SlugChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SlugRoute,
} as any)
const SlugBoardRoute = SlugBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => SlugRoute,
} as any)
const SlugAdminRoute = SlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SlugRoute,
} as any)
const ApiWaitlistIndexRoute = ApiWaitlistIndexRouteImport.update({
  id: '/api/waitlist/',
  path: '/api/waitlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverlayOrgSlugRoute = ApiOverlayOrgSlugRouteImport.update({
  id: '/api/overlay/$orgSlug',
  path: '/api/overlay/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugStreamingPlatformsRoute = SlugStreamingPlatformsRouteImport.update({
  id: '/streaming/platforms',
  path: '/streaming/platforms',
  getParentRoute: () => SlugRoute,
} as any)
const SlugStreamingLtPreviewRoute = SlugStreamingLtPreviewRouteImport.update({
  id: '/streaming/lt-preview',
  path: '/streaming/lt-preview',
  getParentRoute: () => SlugRoute,
} as any)
const SlugStreamingHealthRoute = SlugStreamingHealthRouteImport.update({
  id: '/streaming/health',
  path: '/streaming/health',
  getParentRoute: () => SlugRoute,
} as any)
const SlugStreamingGraphicsRoute = SlugStreamingGraphicsRouteImport.update({
  id: '/streaming/graphics',
  path: '/streaming/graphics',
  getParentRoute: () => SlugRoute,
} as any)
const SlugProductionIncidentsRoute = SlugProductionIncidentsRouteImport.update({
  id: '/production/incidents',
  path: '/production/incidents',
  getParentRoute: () => SlugRoute,
} as any)
const SlugProductionCueSheetsRoute = SlugProductionCueSheetsRouteImport.update({
  id: '/production/cue-sheets',
  path: '/production/cue-sheets',
  getParentRoute: () => SlugRoute,
} as any)
const SlugProductionChecklistRoute = SlugProductionChecklistRouteImport.update({
  id: '/production/checklist',
  path: '/production/checklist',
  getParentRoute: () => SlugRoute,
} as any)
const SlugProductionAssetsRoute = SlugProductionAssetsRouteImport.update({
  id: '/production/assets',
  path: '/production/assets',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDashboardTechManagerRoute =
  SlugDashboardTechManagerRouteImport.update({
    id: '/dashboard/tech-manager',
    path: '/dashboard/tech-manager',
    getParentRoute: () => SlugRoute,
  } as any)
const SlugDashboardProdManagerRoute =
  SlugDashboardProdManagerRouteImport.update({
    id: '/dashboard/prod-manager',
    path: '/dashboard/prod-manager',
    getParentRoute: () => SlugRoute,
  } as any)
const SlugDashboardDevicesRoute = SlugDashboardDevicesRouteImport.update({
  id: '/dashboard/devices',
  path: '/dashboard/devices',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDashboardAudioRoute = SlugDashboardAudioRouteImport.update({
  id: '/dashboard/audio',
  path: '/dashboard/audio',
  getParentRoute: () => SlugRoute,
} as any)
const SlugStreamingGraphicsOverlayRoute =
  SlugStreamingGraphicsOverlayRouteImport.update({
    id: '/overlay',
    path: '/overlay',
    getParentRoute: () => SlugStreamingGraphicsRoute,
  } as any)
const SlugDashboardDevicesDeviceIdRoute =
  SlugDashboardDevicesDeviceIdRouteImport.update({
    id: '/$deviceId',
    path: '/$deviceId',
    getParentRoute: () => SlugDashboardDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/superadmin': typeof SuperadminRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/$slug/board': typeof SlugBoardRoute
  '/$slug/chat': typeof SlugChatRoute
  '/$slug/checkin': typeof SlugCheckinRoute
  '/$slug/crew-chat': typeof SlugCrewChatRoute
  '/$slug/rundown': typeof SlugRundownRoute
  '/$slug/settings': typeof SlugSettingsRoute
  '/$slug/show': typeof SlugShowRoute
  '/$slug/team': typeof SlugTeamRoute
  '/$slug/timecode': typeof SlugTimecodeRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/invitations': typeof AuthInvitationsRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/setup': typeof AuthSetupRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/overlay/$orgSlug': typeof OverlayOrgSlugRoute
  '/timer/$orgSlug': typeof TimerOrgSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/dashboard/audio': typeof SlugDashboardAudioRoute
  '/$slug/dashboard/devices': typeof SlugDashboardDevicesRouteWithChildren
  '/$slug/dashboard/prod-manager': typeof SlugDashboardProdManagerRoute
  '/$slug/dashboard/tech-manager': typeof SlugDashboardTechManagerRoute
  '/$slug/production/assets': typeof SlugProductionAssetsRoute
  '/$slug/production/checklist': typeof SlugProductionChecklistRoute
  '/$slug/production/cue-sheets': typeof SlugProductionCueSheetsRoute
  '/$slug/production/incidents': typeof SlugProductionIncidentsRoute
  '/$slug/streaming/graphics': typeof SlugStreamingGraphicsRouteWithChildren
  '/$slug/streaming/health': typeof SlugStreamingHealthRoute
  '/$slug/streaming/lt-preview': typeof SlugStreamingLtPreviewRoute
  '/$slug/streaming/platforms': typeof SlugStreamingPlatformsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/overlay/$orgSlug': typeof ApiOverlayOrgSlugRoute
  '/api/waitlist/': typeof ApiWaitlistIndexRoute
  '/$slug/dashboard/devices/$deviceId': typeof SlugDashboardDevicesDeviceIdRoute
  '/$slug/streaming/graphics/overlay': typeof SlugStreamingGraphicsOverlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/$slug/board': typeof SlugBoardRoute
  '/$slug/chat': typeof SlugChatRoute
  '/$slug/checkin': typeof SlugCheckinRoute
  '/$slug/crew-chat': typeof SlugCrewChatRoute
  '/$slug/rundown': typeof SlugRundownRoute
  '/$slug/settings': typeof SlugSettingsRoute
  '/$slug/show': typeof SlugShowRoute
  '/$slug/team': typeof SlugTeamRoute
  '/$slug/timecode': typeof SlugTimecodeRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/invitations': typeof AuthInvitationsRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/setup': typeof AuthSetupRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/overlay/$orgSlug': typeof OverlayOrgSlugRoute
  '/timer/$orgSlug': typeof TimerOrgSlugRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/dashboard/audio': typeof SlugDashboardAudioRoute
  '/$slug/dashboard/devices': typeof SlugDashboardDevicesRouteWithChildren
  '/$slug/dashboard/prod-manager': typeof SlugDashboardProdManagerRoute
  '/$slug/dashboard/tech-manager': typeof SlugDashboardTechManagerRoute
  '/$slug/production/assets': typeof SlugProductionAssetsRoute
  '/$slug/production/checklist': typeof SlugProductionChecklistRoute
  '/$slug/production/cue-sheets': typeof SlugProductionCueSheetsRoute
  '/$slug/production/incidents': typeof SlugProductionIncidentsRoute
  '/$slug/streaming/graphics': typeof SlugStreamingGraphicsRouteWithChildren
  '/$slug/streaming/health': typeof SlugStreamingHealthRoute
  '/$slug/streaming/lt-preview': typeof SlugStreamingLtPreviewRoute
  '/$slug/streaming/platforms': typeof SlugStreamingPlatformsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/overlay/$orgSlug': typeof ApiOverlayOrgSlugRoute
  '/api/waitlist': typeof ApiWaitlistIndexRoute
  '/$slug/dashboard/devices/$deviceId': typeof SlugDashboardDevicesDeviceIdRoute
  '/$slug/streaming/graphics/overlay': typeof SlugStreamingGraphicsOverlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/superadmin': typeof SuperadminRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/$slug/board': typeof SlugBoardRoute
  '/$slug/chat': typeof SlugChatRoute
  '/$slug/checkin': typeof SlugCheckinRoute
  '/$slug/crew-chat': typeof SlugCrewChatRoute
  '/$slug/rundown': typeof SlugRundownRoute
  '/$slug/settings': typeof SlugSettingsRoute
  '/$slug/show': typeof SlugShowRoute
  '/$slug/team': typeof SlugTeamRoute
  '/$slug/timecode': typeof SlugTimecodeRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/invitations': typeof AuthInvitationsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/overlay/$orgSlug': typeof OverlayOrgSlugRoute
  '/timer/$orgSlug': typeof TimerOrgSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/dashboard/audio': typeof SlugDashboardAudioRoute
  '/$slug/dashboard/devices': typeof SlugDashboardDevicesRouteWithChildren
  '/$slug/dashboard/prod-manager': typeof SlugDashboardProdManagerRoute
  '/$slug/dashboard/tech-manager': typeof SlugDashboardTechManagerRoute
  '/$slug/production/assets': typeof SlugProductionAssetsRoute
  '/$slug/production/checklist': typeof SlugProductionChecklistRoute
  '/$slug/production/cue-sheets': typeof SlugProductionCueSheetsRoute
  '/$slug/production/incidents': typeof SlugProductionIncidentsRoute
  '/$slug/streaming/graphics': typeof SlugStreamingGraphicsRouteWithChildren
  '/$slug/streaming/health': typeof SlugStreamingHealthRoute
  '/$slug/streaming/lt-preview': typeof SlugStreamingLtPreviewRoute
  '/$slug/streaming/platforms': typeof SlugStreamingPlatformsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/overlay/$orgSlug': typeof ApiOverlayOrgSlugRoute
  '/api/waitlist/': typeof ApiWaitlistIndexRoute
  '/$slug/dashboard/devices/$deviceId': typeof SlugDashboardDevicesDeviceIdRoute
  '/$slug/streaming/graphics/overlay': typeof SlugStreamingGraphicsOverlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/superadmin'
    | '/$slug/admin'
    | '/$slug/board'
    | '/$slug/chat'
    | '/$slug/checkin'
    | '/$slug/crew-chat'
    | '/$slug/rundown'
    | '/$slug/settings'
    | '/$slug/show'
    | '/$slug/team'
    | '/$slug/timecode'
    | '/forgot-password'
    | '/invitations'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/invite/$invitationId'
    | '/overlay/$orgSlug'
    | '/timer/$orgSlug'
    | '/$slug/'
    | '/$slug/dashboard/audio'
    | '/$slug/dashboard/devices'
    | '/$slug/dashboard/prod-manager'
    | '/$slug/dashboard/tech-manager'
    | '/$slug/production/assets'
    | '/$slug/production/checklist'
    | '/$slug/production/cue-sheets'
    | '/$slug/production/incidents'
    | '/$slug/streaming/graphics'
    | '/$slug/streaming/health'
    | '/$slug/streaming/lt-preview'
    | '/$slug/streaming/platforms'
    | '/api/auth/$'
    | '/api/overlay/$orgSlug'
    | '/api/waitlist/'
    | '/$slug/dashboard/devices/$deviceId'
    | '/$slug/streaming/graphics/overlay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/superadmin'
    | '/$slug/admin'
    | '/$slug/board'
    | '/$slug/chat'
    | '/$slug/checkin'
    | '/$slug/crew-chat'
    | '/$slug/rundown'
    | '/$slug/settings'
    | '/$slug/show'
    | '/$slug/team'
    | '/$slug/timecode'
    | '/forgot-password'
    | '/invitations'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/invite/$invitationId'
    | '/overlay/$orgSlug'
    | '/timer/$orgSlug'
    | '/$slug'
    | '/$slug/dashboard/audio'
    | '/$slug/dashboard/devices'
    | '/$slug/dashboard/prod-manager'
    | '/$slug/dashboard/tech-manager'
    | '/$slug/production/assets'
    | '/$slug/production/checklist'
    | '/$slug/production/cue-sheets'
    | '/$slug/production/incidents'
    | '/$slug/streaming/graphics'
    | '/$slug/streaming/health'
    | '/$slug/streaming/lt-preview'
    | '/$slug/streaming/platforms'
    | '/api/auth/$'
    | '/api/overlay/$orgSlug'
    | '/api/waitlist'
    | '/$slug/dashboard/devices/$deviceId'
    | '/$slug/streaming/graphics/overlay'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_auth'
    | '/superadmin'
    | '/$slug/admin'
    | '/$slug/board'
    | '/$slug/chat'
    | '/$slug/checkin'
    | '/$slug/crew-chat'
    | '/$slug/rundown'
    | '/$slug/settings'
    | '/$slug/show'
    | '/$slug/team'
    | '/$slug/timecode'
    | '/_auth/forgot-password'
    | '/_auth/invitations'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/setup'
    | '/invite/$invitationId'
    | '/overlay/$orgSlug'
    | '/timer/$orgSlug'
    | '/$slug/'
    | '/$slug/dashboard/audio'
    | '/$slug/dashboard/devices'
    | '/$slug/dashboard/prod-manager'
    | '/$slug/dashboard/tech-manager'
    | '/$slug/production/assets'
    | '/$slug/production/checklist'
    | '/$slug/production/cue-sheets'
    | '/$slug/production/incidents'
    | '/$slug/streaming/graphics'
    | '/$slug/streaming/health'
    | '/$slug/streaming/lt-preview'
    | '/$slug/streaming/platforms'
    | '/api/auth/$'
    | '/api/overlay/$orgSlug'
    | '/api/waitlist/'
    | '/$slug/dashboard/devices/$deviceId'
    | '/$slug/streaming/graphics/overlay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SuperadminRoute: typeof SuperadminRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  OverlayOrgSlugRoute: typeof OverlayOrgSlugRoute
  TimerOrgSlugRoute: typeof TimerOrgSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOverlayOrgSlugRoute: typeof ApiOverlayOrgSlugRoute
  ApiWaitlistIndexRoute: typeof ApiWaitlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/timer/$orgSlug': {
      id: '/timer/$orgSlug'
      path: '/timer/$orgSlug'
      fullPath: '/timer/$orgSlug'
      preLoaderRoute: typeof TimerOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/$orgSlug': {
      id: '/overlay/$orgSlug'
      path: '/overlay/$orgSlug'
      fullPath: '/overlay/$orgSlug'
      preLoaderRoute: typeof OverlayOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invitations': {
      id: '/_auth/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthInvitationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/$slug/timecode': {
      id: '/$slug/timecode'
      path: '/timecode'
      fullPath: '/$slug/timecode'
      preLoaderRoute: typeof SlugTimecodeRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/team': {
      id: '/$slug/team'
      path: '/team'
      fullPath: '/$slug/team'
      preLoaderRoute: typeof SlugTeamRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/show': {
      id: '/$slug/show'
      path: '/show'
      fullPath: '/$slug/show'
      preLoaderRoute: typeof SlugShowRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/settings': {
      id: '/$slug/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof SlugSettingsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/rundown': {
      id: '/$slug/rundown'
      path: '/rundown'
      fullPath: '/$slug/rundown'
      preLoaderRoute: typeof SlugRundownRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/crew-chat': {
      id: '/$slug/crew-chat'
      path: '/crew-chat'
      fullPath: '/$slug/crew-chat'
      preLoaderRoute: typeof SlugCrewChatRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/checkin': {
      id: '/$slug/checkin'
      path: '/checkin'
      fullPath: '/$slug/checkin'
      preLoaderRoute: typeof SlugCheckinRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/chat': {
      id: '/$slug/chat'
      path: '/chat'
      fullPath: '/$slug/chat'
      preLoaderRoute: typeof SlugChatRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/board': {
      id: '/$slug/board'
      path: '/board'
      fullPath: '/$slug/board'
      preLoaderRoute: typeof SlugBoardRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/admin': {
      id: '/$slug/admin'
      path: '/admin'
      fullPath: '/$slug/admin'
      preLoaderRoute: typeof SlugAdminRouteImport
      parentRoute: typeof SlugRoute
    }
    '/api/waitlist/': {
      id: '/api/waitlist/'
      path: '/api/waitlist'
      fullPath: '/api/waitlist/'
      preLoaderRoute: typeof ApiWaitlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overlay/$orgSlug': {
      id: '/api/overlay/$orgSlug'
      path: '/api/overlay/$orgSlug'
      fullPath: '/api/overlay/$orgSlug'
      preLoaderRoute: typeof ApiOverlayOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/streaming/platforms': {
      id: '/$slug/streaming/platforms'
      path: '/streaming/platforms'
      fullPath: '/$slug/streaming/platforms'
      preLoaderRoute: typeof SlugStreamingPlatformsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/streaming/lt-preview': {
      id: '/$slug/streaming/lt-preview'
      path: '/streaming/lt-preview'
      fullPath: '/$slug/streaming/lt-preview'
      preLoaderRoute: typeof SlugStreamingLtPreviewRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/streaming/health': {
      id: '/$slug/streaming/health'
      path: '/streaming/health'
      fullPath: '/$slug/streaming/health'
      preLoaderRoute: typeof SlugStreamingHealthRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/streaming/graphics': {
      id: '/$slug/streaming/graphics'
      path: '/streaming/graphics'
      fullPath: '/$slug/streaming/graphics'
      preLoaderRoute: typeof SlugStreamingGraphicsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/production/incidents': {
      id: '/$slug/production/incidents'
      path: '/production/incidents'
      fullPath: '/$slug/production/incidents'
      preLoaderRoute: typeof SlugProductionIncidentsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/production/cue-sheets': {
      id: '/$slug/production/cue-sheets'
      path: '/production/cue-sheets'
      fullPath: '/$slug/production/cue-sheets'
      preLoaderRoute: typeof SlugProductionCueSheetsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/production/checklist': {
      id: '/$slug/production/checklist'
      path: '/production/checklist'
      fullPath: '/$slug/production/checklist'
      preLoaderRoute: typeof SlugProductionChecklistRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/production/assets': {
      id: '/$slug/production/assets'
      path: '/production/assets'
      fullPath: '/$slug/production/assets'
      preLoaderRoute: typeof SlugProductionAssetsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/dashboard/tech-manager': {
      id: '/$slug/dashboard/tech-manager'
      path: '/dashboard/tech-manager'
      fullPath: '/$slug/dashboard/tech-manager'
      preLoaderRoute: typeof SlugDashboardTechManagerRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/dashboard/prod-manager': {
      id: '/$slug/dashboard/prod-manager'
      path: '/dashboard/prod-manager'
      fullPath: '/$slug/dashboard/prod-manager'
      preLoaderRoute: typeof SlugDashboardProdManagerRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/dashboard/devices': {
      id: '/$slug/dashboard/devices'
      path: '/dashboard/devices'
      fullPath: '/$slug/dashboard/devices'
      preLoaderRoute: typeof SlugDashboardDevicesRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/dashboard/audio': {
      id: '/$slug/dashboard/audio'
      path: '/dashboard/audio'
      fullPath: '/$slug/dashboard/audio'
      preLoaderRoute: typeof SlugDashboardAudioRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/streaming/graphics/overlay': {
      id: '/$slug/streaming/graphics/overlay'
      path: '/overlay'
      fullPath: '/$slug/streaming/graphics/overlay'
      preLoaderRoute: typeof SlugStreamingGraphicsOverlayRouteImport
      parentRoute: typeof SlugStreamingGraphicsRoute
    }
    '/$slug/dashboard/devices/$deviceId': {
      id: '/$slug/dashboard/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/$slug/dashboard/devices/$deviceId'
      preLoaderRoute: typeof SlugDashboardDevicesDeviceIdRouteImport
      parentRoute: typeof SlugDashboardDevicesRoute
    }
  }
}

interface SlugDashboardDevicesRouteChildren {
  SlugDashboardDevicesDeviceIdRoute: typeof SlugDashboardDevicesDeviceIdRoute
}

const SlugDashboardDevicesRouteChildren: SlugDashboardDevicesRouteChildren = {
  SlugDashboardDevicesDeviceIdRoute: SlugDashboardDevicesDeviceIdRoute,
}

const SlugDashboardDevicesRouteWithChildren =
  SlugDashboardDevicesRoute._addFileChildren(SlugDashboardDevicesRouteChildren)

interface SlugStreamingGraphicsRouteChildren {
  SlugStreamingGraphicsOverlayRoute: typeof SlugStreamingGraphicsOverlayRoute
}

const SlugStreamingGraphicsRouteChildren: SlugStreamingGraphicsRouteChildren = {
  SlugStreamingGraphicsOverlayRoute: SlugStreamingGraphicsOverlayRoute,
}

const SlugStreamingGraphicsRouteWithChildren =
  SlugStreamingGraphicsRoute._addFileChildren(
    SlugStreamingGraphicsRouteChildren,
  )

interface SlugRouteChildren {
  SlugAdminRoute: typeof SlugAdminRoute
  SlugBoardRoute: typeof SlugBoardRoute
  SlugChatRoute: typeof SlugChatRoute
  SlugCheckinRoute: typeof SlugCheckinRoute
  SlugCrewChatRoute: typeof SlugCrewChatRoute
  SlugRundownRoute: typeof SlugRundownRoute
  SlugSettingsRoute: typeof SlugSettingsRoute
  SlugShowRoute: typeof SlugShowRoute
  SlugTeamRoute: typeof SlugTeamRoute
  SlugTimecodeRoute: typeof SlugTimecodeRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugDashboardAudioRoute: typeof SlugDashboardAudioRoute
  SlugDashboardDevicesRoute: typeof SlugDashboardDevicesRouteWithChildren
  SlugDashboardProdManagerRoute: typeof SlugDashboardProdManagerRoute
  SlugDashboardTechManagerRoute: typeof SlugDashboardTechManagerRoute
  SlugProductionAssetsRoute: typeof SlugProductionAssetsRoute
  SlugProductionChecklistRoute: typeof SlugProductionChecklistRoute
  SlugProductionCueSheetsRoute: typeof SlugProductionCueSheetsRoute
  SlugProductionIncidentsRoute: typeof SlugProductionIncidentsRoute
  SlugStreamingGraphicsRoute: typeof SlugStreamingGraphicsRouteWithChildren
  SlugStreamingHealthRoute: typeof SlugStreamingHealthRoute
  SlugStreamingLtPreviewRoute: typeof SlugStreamingLtPreviewRoute
  SlugStreamingPlatformsRoute: typeof SlugStreamingPlatformsRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugAdminRoute: SlugAdminRoute,
  SlugBoardRoute: SlugBoardRoute,
  SlugChatRoute: SlugChatRoute,
  SlugCheckinRoute: SlugCheckinRoute,
  SlugCrewChatRoute: SlugCrewChatRoute,
  SlugRundownRoute: SlugRundownRoute,
  SlugSettingsRoute: SlugSettingsRoute,
  SlugShowRoute: SlugShowRoute,
  SlugTeamRoute: SlugTeamRoute,
  SlugTimecodeRoute: SlugTimecodeRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugDashboardAudioRoute: SlugDashboardAudioRoute,
  SlugDashboardDevicesRoute: SlugDashboardDevicesRouteWithChildren,
  SlugDashboardProdManagerRoute: SlugDashboardProdManagerRoute,
  SlugDashboardTechManagerRoute: SlugDashboardTechManagerRoute,
  SlugProductionAssetsRoute: SlugProductionAssetsRoute,
  SlugProductionChecklistRoute: SlugProductionChecklistRoute,
  SlugProductionCueSheetsRoute: SlugProductionCueSheetsRoute,
  SlugProductionIncidentsRoute: SlugProductionIncidentsRoute,
  SlugStreamingGraphicsRoute: SlugStreamingGraphicsRouteWithChildren,
  SlugStreamingHealthRoute: SlugStreamingHealthRoute,
  SlugStreamingLtPreviewRoute: SlugStreamingLtPreviewRoute,
  SlugStreamingPlatformsRoute: SlugStreamingPlatformsRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthInvitationsRoute: typeof AuthInvitationsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthInvitationsRoute: AuthInvitationsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SuperadminRoute: SuperadminRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  OverlayOrgSlugRoute: OverlayOrgSlugRoute,
  TimerOrgSlugRoute: TimerOrgSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOverlayOrgSlugRoute: ApiOverlayOrgSlugRoute,
  ApiWaitlistIndexRoute: ApiWaitlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
