/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as SlugShowRouteImport } from './routes/$slug/show'
import { Route as SlugCheckinRouteImport } from './routes/$slug/checkin'
import { Route as SlugAdminRouteImport } from './routes/$slug/admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SlugStreamingPlatformsRouteImport } from './routes/$slug/streaming/platforms'
import { Route as SlugStreamingHealthRouteImport } from './routes/$slug/streaming/health'
import { Route as SlugStreamingGraphicsRouteImport } from './routes/$slug/streaming/graphics'
import { Route as SlugShowBoardRouteImport } from './routes/$slug/show/board'
import { Route as SlugProductionIncidentsRouteImport } from './routes/$slug/production/incidents'
import { Route as SlugProductionCueSheetsRouteImport } from './routes/$slug/production/cue-sheets'
import { Route as SlugProductionChecklistRouteImport } from './routes/$slug/production/checklist'
import { Route as SlugProductionAssetsRouteImport } from './routes/$slug/production/assets'
import { Route as SlugDashboardTechManagerRouteImport } from './routes/$slug/dashboard/tech-manager'
import { Route as SlugDashboardProdManagerRouteImport } from './routes/$slug/dashboard/prod-manager'
import { Route as SlugDashboardDevicesRouteImport } from './routes/$slug/dashboard/devices'
import { Route as SlugDashboardAudioRouteImport } from './routes/$slug/dashboard/audio'
import { Route as SlugStreamingGraphicsOverlayRouteImport } from './routes/$slug/streaming/graphics/overlay'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const SlugShowRoute = SlugShowRouteImport.update({
  id: '/show',
  path: '/show',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCheckinRoute = SlugCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => SlugRoute,
} as any)
const SlugAdminRoute = SlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SlugRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugStreamingPlatformsRoute = SlugStreamingPlatformsRouteImport.update({
  id: '/streaming/platforms',
  path: '/streaming/platforms',
  getParentRoute: () => SlugRoute,
} as any)
const SlugStreamingHealthRoute = SlugStreamingHealthRouteImport.update({
  id: '/streaming/health',
  path: '/streaming/health',
  getParentRoute: () => SlugRoute,
} as any)
const SlugStreamingGraphicsRoute = SlugStreamingGraphicsRouteImport.update({
  id: '/streaming/graphics',
  path: '/streaming/graphics',
  getParentRoute: () => SlugRoute,
} as any)
const SlugShowBoardRoute = SlugShowBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => SlugShowRoute,
} as any)
const SlugProductionIncidentsRoute = SlugProductionIncidentsRouteImport.update({
  id: '/production/incidents',
  path: '/production/incidents',
  getParentRoute: () => SlugRoute,
} as any)
const SlugProductionCueSheetsRoute = SlugProductionCueSheetsRouteImport.update({
  id: '/production/cue-sheets',
  path: '/production/cue-sheets',
  getParentRoute: () => SlugRoute,
} as any)
const SlugProductionChecklistRoute = SlugProductionChecklistRouteImport.update({
  id: '/production/checklist',
  path: '/production/checklist',
  getParentRoute: () => SlugRoute,
} as any)
const SlugProductionAssetsRoute = SlugProductionAssetsRouteImport.update({
  id: '/production/assets',
  path: '/production/assets',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDashboardTechManagerRoute =
  SlugDashboardTechManagerRouteImport.update({
    id: '/dashboard/tech-manager',
    path: '/dashboard/tech-manager',
    getParentRoute: () => SlugRoute,
  } as any)
const SlugDashboardProdManagerRoute =
  SlugDashboardProdManagerRouteImport.update({
    id: '/dashboard/prod-manager',
    path: '/dashboard/prod-manager',
    getParentRoute: () => SlugRoute,
  } as any)
const SlugDashboardDevicesRoute = SlugDashboardDevicesRouteImport.update({
  id: '/dashboard/devices',
  path: '/dashboard/devices',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDashboardAudioRoute = SlugDashboardAudioRouteImport.update({
  id: '/dashboard/audio',
  path: '/dashboard/audio',
  getParentRoute: () => SlugRoute,
} as any)
const SlugStreamingGraphicsOverlayRoute =
  SlugStreamingGraphicsOverlayRouteImport.update({
    id: '/overlay',
    path: '/overlay',
    getParentRoute: () => SlugStreamingGraphicsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/$slug/admin': typeof SlugAdminRoute
  '/$slug/checkin': typeof SlugCheckinRoute
  '/$slug/show': typeof SlugShowRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/dashboard/audio': typeof SlugDashboardAudioRoute
  '/$slug/dashboard/devices': typeof SlugDashboardDevicesRoute
  '/$slug/dashboard/prod-manager': typeof SlugDashboardProdManagerRoute
  '/$slug/dashboard/tech-manager': typeof SlugDashboardTechManagerRoute
  '/$slug/production/assets': typeof SlugProductionAssetsRoute
  '/$slug/production/checklist': typeof SlugProductionChecklistRoute
  '/$slug/production/cue-sheets': typeof SlugProductionCueSheetsRoute
  '/$slug/production/incidents': typeof SlugProductionIncidentsRoute
  '/$slug/show/board': typeof SlugShowBoardRoute
  '/$slug/streaming/graphics': typeof SlugStreamingGraphicsRouteWithChildren
  '/$slug/streaming/health': typeof SlugStreamingHealthRoute
  '/$slug/streaming/platforms': typeof SlugStreamingPlatformsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/streaming/graphics/overlay': typeof SlugStreamingGraphicsOverlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/$slug/checkin': typeof SlugCheckinRoute
  '/$slug/show': typeof SlugShowRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/dashboard/audio': typeof SlugDashboardAudioRoute
  '/$slug/dashboard/devices': typeof SlugDashboardDevicesRoute
  '/$slug/dashboard/prod-manager': typeof SlugDashboardProdManagerRoute
  '/$slug/dashboard/tech-manager': typeof SlugDashboardTechManagerRoute
  '/$slug/production/assets': typeof SlugProductionAssetsRoute
  '/$slug/production/checklist': typeof SlugProductionChecklistRoute
  '/$slug/production/cue-sheets': typeof SlugProductionCueSheetsRoute
  '/$slug/production/incidents': typeof SlugProductionIncidentsRoute
  '/$slug/show/board': typeof SlugShowBoardRoute
  '/$slug/streaming/graphics': typeof SlugStreamingGraphicsRouteWithChildren
  '/$slug/streaming/health': typeof SlugStreamingHealthRoute
  '/$slug/streaming/platforms': typeof SlugStreamingPlatformsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/streaming/graphics/overlay': typeof SlugStreamingGraphicsOverlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/$slug/admin': typeof SlugAdminRoute
  '/$slug/checkin': typeof SlugCheckinRoute
  '/$slug/show': typeof SlugShowRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/dashboard/audio': typeof SlugDashboardAudioRoute
  '/$slug/dashboard/devices': typeof SlugDashboardDevicesRoute
  '/$slug/dashboard/prod-manager': typeof SlugDashboardProdManagerRoute
  '/$slug/dashboard/tech-manager': typeof SlugDashboardTechManagerRoute
  '/$slug/production/assets': typeof SlugProductionAssetsRoute
  '/$slug/production/checklist': typeof SlugProductionChecklistRoute
  '/$slug/production/cue-sheets': typeof SlugProductionCueSheetsRoute
  '/$slug/production/incidents': typeof SlugProductionIncidentsRoute
  '/$slug/show/board': typeof SlugShowBoardRoute
  '/$slug/streaming/graphics': typeof SlugStreamingGraphicsRouteWithChildren
  '/$slug/streaming/health': typeof SlugStreamingHealthRoute
  '/$slug/streaming/platforms': typeof SlugStreamingPlatformsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/streaming/graphics/overlay': typeof SlugStreamingGraphicsOverlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/$slug/admin'
    | '/$slug/checkin'
    | '/$slug/show'
    | '/login'
    | '/setup'
    | '/$slug/'
    | '/$slug/dashboard/audio'
    | '/$slug/dashboard/devices'
    | '/$slug/dashboard/prod-manager'
    | '/$slug/dashboard/tech-manager'
    | '/$slug/production/assets'
    | '/$slug/production/checklist'
    | '/$slug/production/cue-sheets'
    | '/$slug/production/incidents'
    | '/$slug/show/board'
    | '/$slug/streaming/graphics'
    | '/$slug/streaming/health'
    | '/$slug/streaming/platforms'
    | '/api/auth/$'
    | '/$slug/streaming/graphics/overlay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug/admin'
    | '/$slug/checkin'
    | '/$slug/show'
    | '/login'
    | '/setup'
    | '/$slug'
    | '/$slug/dashboard/audio'
    | '/$slug/dashboard/devices'
    | '/$slug/dashboard/prod-manager'
    | '/$slug/dashboard/tech-manager'
    | '/$slug/production/assets'
    | '/$slug/production/checklist'
    | '/$slug/production/cue-sheets'
    | '/$slug/production/incidents'
    | '/$slug/show/board'
    | '/$slug/streaming/graphics'
    | '/$slug/streaming/health'
    | '/$slug/streaming/platforms'
    | '/api/auth/$'
    | '/$slug/streaming/graphics/overlay'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_auth'
    | '/$slug/admin'
    | '/$slug/checkin'
    | '/$slug/show'
    | '/_auth/login'
    | '/_auth/setup'
    | '/$slug/'
    | '/$slug/dashboard/audio'
    | '/$slug/dashboard/devices'
    | '/$slug/dashboard/prod-manager'
    | '/$slug/dashboard/tech-manager'
    | '/$slug/production/assets'
    | '/$slug/production/checklist'
    | '/$slug/production/cue-sheets'
    | '/$slug/production/incidents'
    | '/$slug/show/board'
    | '/$slug/streaming/graphics'
    | '/$slug/streaming/health'
    | '/$slug/streaming/platforms'
    | '/api/auth/$'
    | '/$slug/streaming/graphics/overlay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/$slug/show': {
      id: '/$slug/show'
      path: '/show'
      fullPath: '/$slug/show'
      preLoaderRoute: typeof SlugShowRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/checkin': {
      id: '/$slug/checkin'
      path: '/checkin'
      fullPath: '/$slug/checkin'
      preLoaderRoute: typeof SlugCheckinRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/admin': {
      id: '/$slug/admin'
      path: '/admin'
      fullPath: '/$slug/admin'
      preLoaderRoute: typeof SlugAdminRouteImport
      parentRoute: typeof SlugRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/streaming/platforms': {
      id: '/$slug/streaming/platforms'
      path: '/streaming/platforms'
      fullPath: '/$slug/streaming/platforms'
      preLoaderRoute: typeof SlugStreamingPlatformsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/streaming/health': {
      id: '/$slug/streaming/health'
      path: '/streaming/health'
      fullPath: '/$slug/streaming/health'
      preLoaderRoute: typeof SlugStreamingHealthRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/streaming/graphics': {
      id: '/$slug/streaming/graphics'
      path: '/streaming/graphics'
      fullPath: '/$slug/streaming/graphics'
      preLoaderRoute: typeof SlugStreamingGraphicsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/show/board': {
      id: '/$slug/show/board'
      path: '/board'
      fullPath: '/$slug/show/board'
      preLoaderRoute: typeof SlugShowBoardRouteImport
      parentRoute: typeof SlugShowRoute
    }
    '/$slug/production/incidents': {
      id: '/$slug/production/incidents'
      path: '/production/incidents'
      fullPath: '/$slug/production/incidents'
      preLoaderRoute: typeof SlugProductionIncidentsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/production/cue-sheets': {
      id: '/$slug/production/cue-sheets'
      path: '/production/cue-sheets'
      fullPath: '/$slug/production/cue-sheets'
      preLoaderRoute: typeof SlugProductionCueSheetsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/production/checklist': {
      id: '/$slug/production/checklist'
      path: '/production/checklist'
      fullPath: '/$slug/production/checklist'
      preLoaderRoute: typeof SlugProductionChecklistRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/production/assets': {
      id: '/$slug/production/assets'
      path: '/production/assets'
      fullPath: '/$slug/production/assets'
      preLoaderRoute: typeof SlugProductionAssetsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/dashboard/tech-manager': {
      id: '/$slug/dashboard/tech-manager'
      path: '/dashboard/tech-manager'
      fullPath: '/$slug/dashboard/tech-manager'
      preLoaderRoute: typeof SlugDashboardTechManagerRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/dashboard/prod-manager': {
      id: '/$slug/dashboard/prod-manager'
      path: '/dashboard/prod-manager'
      fullPath: '/$slug/dashboard/prod-manager'
      preLoaderRoute: typeof SlugDashboardProdManagerRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/dashboard/devices': {
      id: '/$slug/dashboard/devices'
      path: '/dashboard/devices'
      fullPath: '/$slug/dashboard/devices'
      preLoaderRoute: typeof SlugDashboardDevicesRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/dashboard/audio': {
      id: '/$slug/dashboard/audio'
      path: '/dashboard/audio'
      fullPath: '/$slug/dashboard/audio'
      preLoaderRoute: typeof SlugDashboardAudioRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/streaming/graphics/overlay': {
      id: '/$slug/streaming/graphics/overlay'
      path: '/overlay'
      fullPath: '/$slug/streaming/graphics/overlay'
      preLoaderRoute: typeof SlugStreamingGraphicsOverlayRouteImport
      parentRoute: typeof SlugStreamingGraphicsRoute
    }
  }
}

interface SlugShowRouteChildren {
  SlugShowBoardRoute: typeof SlugShowBoardRoute
}

const SlugShowRouteChildren: SlugShowRouteChildren = {
  SlugShowBoardRoute: SlugShowBoardRoute,
}

const SlugShowRouteWithChildren = SlugShowRoute._addFileChildren(
  SlugShowRouteChildren,
)

interface SlugStreamingGraphicsRouteChildren {
  SlugStreamingGraphicsOverlayRoute: typeof SlugStreamingGraphicsOverlayRoute
}

const SlugStreamingGraphicsRouteChildren: SlugStreamingGraphicsRouteChildren = {
  SlugStreamingGraphicsOverlayRoute: SlugStreamingGraphicsOverlayRoute,
}

const SlugStreamingGraphicsRouteWithChildren =
  SlugStreamingGraphicsRoute._addFileChildren(
    SlugStreamingGraphicsRouteChildren,
  )

interface SlugRouteChildren {
  SlugAdminRoute: typeof SlugAdminRoute
  SlugCheckinRoute: typeof SlugCheckinRoute
  SlugShowRoute: typeof SlugShowRouteWithChildren
  SlugIndexRoute: typeof SlugIndexRoute
  SlugDashboardAudioRoute: typeof SlugDashboardAudioRoute
  SlugDashboardDevicesRoute: typeof SlugDashboardDevicesRoute
  SlugDashboardProdManagerRoute: typeof SlugDashboardProdManagerRoute
  SlugDashboardTechManagerRoute: typeof SlugDashboardTechManagerRoute
  SlugProductionAssetsRoute: typeof SlugProductionAssetsRoute
  SlugProductionChecklistRoute: typeof SlugProductionChecklistRoute
  SlugProductionCueSheetsRoute: typeof SlugProductionCueSheetsRoute
  SlugProductionIncidentsRoute: typeof SlugProductionIncidentsRoute
  SlugStreamingGraphicsRoute: typeof SlugStreamingGraphicsRouteWithChildren
  SlugStreamingHealthRoute: typeof SlugStreamingHealthRoute
  SlugStreamingPlatformsRoute: typeof SlugStreamingPlatformsRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugAdminRoute: SlugAdminRoute,
  SlugCheckinRoute: SlugCheckinRoute,
  SlugShowRoute: SlugShowRouteWithChildren,
  SlugIndexRoute: SlugIndexRoute,
  SlugDashboardAudioRoute: SlugDashboardAudioRoute,
  SlugDashboardDevicesRoute: SlugDashboardDevicesRoute,
  SlugDashboardProdManagerRoute: SlugDashboardProdManagerRoute,
  SlugDashboardTechManagerRoute: SlugDashboardTechManagerRoute,
  SlugProductionAssetsRoute: SlugProductionAssetsRoute,
  SlugProductionChecklistRoute: SlugProductionChecklistRoute,
  SlugProductionCueSheetsRoute: SlugProductionCueSheetsRoute,
  SlugProductionIncidentsRoute: SlugProductionIncidentsRoute,
  SlugStreamingGraphicsRoute: SlugStreamingGraphicsRouteWithChildren,
  SlugStreamingHealthRoute: SlugStreamingHealthRoute,
  SlugStreamingPlatformsRoute: SlugStreamingPlatformsRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
