import { type ModuleId, type WorkspaceType } from "./types";
export const CORE_MODULES: readonly ModuleId[] = ["show", "rundown", "team"];
export const WORKSPACE_MODULES = {
  show: "Show",
  rundown: "Rundown",
  team: "Team",
  schedule: "Schedule",
  board: "Show Board & Check-in",
  chat: "Chat",
  production: "Production",
  timecode: "Timecode",
  songs: "Songs",
  streaming: "Streaming",
  lower_thirds: "Lower Thirds",
  dashboards: "Dashboards",
} satisfies Record<ModuleId, string>;
export const WORKSPACE_DEFINITIONS = {
  church: {
    label: "Church",
    description: "Services, worship, weekend production",
    icon: "Church",
    customizable: false,
  },
  live_events: {
    label: "Live Events",
    description: "Conferences, concerts, corporate shows",
    icon: "RadioTower",
    customizable: false,
  },
  school: {
    label: "School",
    description: "Assemblies, graduations, campus media",
    icon: "GraduationCap",
    customizable: false,
  },
  theatre: {
    label: "Theatre",
    description: "Performances and cue-driven shows",
    icon: "Drama",
    customizable: false,
  },
  custom: {
    label: "Custom",
    description: "Pick your own features and names",
    icon: "SlidersHorizontal",
    customizable: true,
  },
} as const satisfies Record<
  WorkspaceType,
  { label: string; description: string; icon: string; customizable: boolean }
>;
export const DEFAULT_WORKSPACE_MODULES: Record<
  WorkspaceType,
  readonly ModuleId[]
> = {
  church: [
    "show",
    "rundown",
    "team",
    "schedule",
    "board",
    "chat",
    "production",
    "timecode",
    "songs",
    "streaming",
    "lower_thirds",
    "dashboards",
  ],
  live_events: [
    "show",
    "rundown",
    "team",
    "schedule",
    "board",
    "chat",
    "production",
    "timecode",
    "streaming",
    "lower_thirds",
    "dashboards",
  ],
  school: [
    "show",
    "rundown",
    "team",
    "schedule",
    "board",
    "chat",
    "production",
    "streaming",
    "lower_thirds",
    "dashboards",
  ],
  theatre: [
    "show",
    "rundown",
    "team",
    "schedule",
    "board",
    "chat",
    "production",
    "timecode",
    "dashboards",
  ],
  custom: [
    "show",
    "rundown",
    "team",
    "schedule",
    "board",
    "chat",
    "production",
    "timecode",
    "songs",
    "streaming",
    "lower_thirds",
    "dashboards",
  ],
};
