import type { WorkspaceType, WorkspaceTerms } from "./types";
export const WORKSPACE_TERMS = {
  church: {
    event: "service",
    eventTitle: "Service",
    eventPlural: "Services",
    eventName: "Service name",
    participate: "serve",
    scheduled: "You've been scheduled to serve",
    checkinCta: "Scan to Serve",
    section: "Set",
    item: "Element",
    itemPlural: "Elements",
    presenter: "Speaker",
    presenterExample: "Pastor James",
    sectionExample: "Worship Set",
    eventNameExample: "Sunday Morning",
  },
  live_events: {
    event: "show",
    eventTitle: "Show",
    eventPlural: "Shows",
    eventName: "Show name",
    participate: "work this show",
    scheduled: "You've been assigned",
    checkinCta: "Scan to Check In",
    section: "Block",
    item: "Segment",
    itemPlural: "Segments",
    presenter: "Presenter",
    presenterExample: "Jordan Lee, CEO",
    sectionExample: "Keynote Block",
    eventNameExample: "Product Launch Keynote",
  },
  school: {
    event: "event",
    eventTitle: "Event",
    eventPlural: "Events",
    eventName: "Event name",
    participate: "work this event",
    scheduled: "You've been assigned",
    checkinCta: "Scan to Check In",
    section: "Block",
    item: "Segment",
    itemPlural: "Segments",
    presenter: "Presenter",
    presenterExample: "Principal Adams",
    sectionExample: "Awards Block",
    eventNameExample: "Spring Assembly",
  },
  theatre: {
    event: "performance",
    eventTitle: "Performance",
    eventPlural: "Performances",
    eventName: "Performance name",
    participate: "work this performance",
    scheduled: "You've been called",
    checkinCta: "Scan to Sign In",
    section: "Act",
    item: "Cue",
    itemPlural: "Cues",
    presenter: "Performer",
    presenterExample: "Lead — Maria",
    sectionExample: "Act 1",
    eventNameExample: "Opening Night",
  },
  custom: {
    event: "show",
    eventTitle: "Show",
    eventPlural: "Shows",
    eventName: "Show name",
    participate: "work this show",
    scheduled: "You've been assigned",
    checkinCta: "Scan to Check In",
    section: "Block",
    item: "Segment",
    itemPlural: "Segments",
    presenter: "Presenter",
    presenterExample: "Jordan Lee",
    sectionExample: "Main Block",
    eventNameExample: "Main Show",
  },
} satisfies Record<WorkspaceType, WorkspaceTerms>;
